version: 2

before:
  hooks:
    - sh -c "cd projectsCLI && go mod tidy"

builds:
  - id: projects
    dir: projectsCLI
    main: ./cmd/projects
    binary: projects
    env:
      - CGO_ENABLED=0
    ldflags:
      - -s -w -X main.version={{.Version}}
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64

archives:
  - id: projects
    builds:
      - projects
    format: tar.gz
    name_template: "projects_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    format_overrides:
      - goos: windows
        format: zip

checksum:
  name_template: "checksums.txt"

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^ci:"
      - "^chore:"

brews:
  - name: projects
    ids:
      - projects
    repository:
      owner: jackmorganxyz
      name: homebrew-tap
      token: "{{ .Env.HOMEBREW_TAP_GITHUB_TOKEN }}"
    directory: Formula
    homepage: "https://github.com/jackmorganxyz/projectsCLI"
    description: "Manage project scaffolds from the command line"
    license: "MIT"
    install: |
      bin.install "projects"
    test: |
      system "#{bin}/projects", "--version"

release:
  github:
    owner: jackmorganxyz
    name: projectsCLI
  name_template: "v{{.Version}}"
