version: 2

before:
  hooks:
    - go mod tidy

builds:
  - id: projctl
    dir: projctl
    main: ./cmd/projctl
    binary: projctl
    env:
      - CGO_ENABLED=0
    ldflags:
      - -s -w -X main.version={{.Version}}
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64

archives:
  - id: projctl
    builds:
      - projctl
    format: tar.gz
    name_template: "projctl_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    format_overrides:
      - goos: windows
        format: zip

checksum:
  name_template: "checksums.txt"

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^ci:"
      - "^chore:"

brews:
  - ids:
      - projctl
    repository:
      owner: jackpmorgan
      name: homebrew-tap
      token: "{{ .Env.HOMEBREW_TAP_GITHUB_TOKEN }}"
    directory: Formula
    homepage: "https://github.com/jackpmorgan/projects-cli"
    description: "Manage project scaffolds from the command line"
    license: "MIT"
    install: |
      bin.install "projctl"
    test: |
      system "#{bin}/projctl", "--version"

release:
  github:
    owner: jackpmorgan
    name: projects-cli
  name_template: "v{{.Version}}"
