version: 2

before:
  hooks:
    - cd projectsCLI && go mod tidy

builds:
  - id: projectsCLI
    dir: projectsCLI
    main: ./cmd/projectsCLI
    binary: projectsCLI
    env:
      - CGO_ENABLED=0
    ldflags:
      - -s -w -X main.version={{.Version}}
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64

archives:
  - id: projectsCLI
    builds:
      - projectsCLI
    format: tar.gz
    name_template: "projectsCLI_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    format_overrides:
      - goos: windows
        format: zip

checksum:
  name_template: "checksums.txt"

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^ci:"
      - "^chore:"

brews:
  - ids:
      - projectsCLI
    repository:
      owner: jackmorganxyz
      name: homebrew-tap
      token: "{{ .Env.HOMEBREW_TAP_GITHUB_TOKEN }}"
    directory: Formula
    homepage: "https://github.com/jackmorganxyz/projectsCLI"
    description: "Manage project scaffolds from the command line"
    license: "MIT"
    install: |
      bin.install "projectsCLI"
    test: |
      system "#{bin}/projectsCLI", "--version"

release:
  github:
    owner: jackmorganxyz
    name: projectsCLI
  name_template: "v{{.Version}}"
