name: Bug Report
description: Report a bug in projectsCLI
title: "[Bug]: "
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for reporting! Please fill in the details below.
  - type: input
    id: version
    attributes:
      label: projectsCLI version
      description: "Run `projectsCLI --version` and paste the output"
      placeholder: "v0.1.0"
    validations:
      required: true
  - type: dropdown
    id: os
    attributes:
      label: Operating System
      options:
        - macOS (Apple Silicon)
        - macOS (Intel)
        - Linux (amd64)
        - Linux (arm64)
        - Windows
        - Other
    validations:
      required: true
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: "Describe the bug. What did you expect vs what actually happened?"
    validations:
      required: true
  - type: textarea
    id: reproduce
    attributes:
      label: Steps to reproduce
      description: "Minimal steps to reproduce the issue"
      value: |
        1. Run `projectsCLI ...`
        2. ...
    validations:
      required: true
  - type: textarea
    id: output
    attributes:
      label: Terminal output
      description: "Paste any relevant terminal output (use --json if possible)"
      render: shell
  - type: dropdown
    id: install-method
    attributes:
      label: Installation method
      options:
        - Homebrew
        - curl install script
        - Built from source
        - Go install
