name: Feature Request
description: Suggest a new feature or improvement
title: "[Feature]: "
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        Feature ideas welcome! The best ones come with a clear use case.
  - type: textarea
    id: problem
    attributes:
      label: What problem does this solve?
      description: "Describe the pain point or use case"
    validations:
      required: true
  - type: textarea
    id: solution
    attributes:
      label: Proposed solution
      description: "How would you like this to work? CLI examples are great."
  - type: dropdown
    id: audience
    attributes:
      label: Who is this for?
      options:
        - Human users (TUI experience)
        - AI agents / scripts (JSON interface)
        - Both
    validations:
      required: true
  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives considered
      description: "Any workarounds or alternative approaches?"
